# Verwenden Sie das offizielle Python-Image als Basisimage
FROM python:3.9-slim

# Setzen Sie das Arbeitsverzeichnis innerhalb des Containers
WORKDIR /app

# Kopieren Sie die requirements.txt-Datei in das Arbeitsverzeichnis
COPY requirements.txt .

# Installieren Sie die Python-Abhängigkeiten
RUN pip install --no-cache-dir -r requirements.txt

# Kopieren Sie den restlichen Anwendungscode in das Arbeitsverzeichnis
COPY . .

# Kopieren Sie die Dateien aus dem Vorlagenordner in das Arbeitsverzeichnis
COPY templates/index.html .
COPY static/pokemon.html .
COPY static/style.css .
COPY static/script.js .
COPY static/bilder .
COPY static/static/bilder .

# Geben Sie den Port frei, auf dem die Flask-Anwendung ausgeführt wird
EXPOSE 3000

# Starten Sie die Flask-Anwendung
CMD ["python", "app.py"]
